
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <Navbar />

        {/* Main container with flex-grow to take up remaining space */}
        <div className="flex-grow container mx-auto px-4">
          {children}
        </div>

        <Footer />
      </body>
    </html>
  );
}
